name: YouTube Audio Streaming
version: "1.0.0"
slug: youtube_audio_streaming
description: Stream audio from YouTube videos
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  5000/tcp: 5000
options: {}
schema: {}
build_from:
  aarch64: "ghcr.io/hassio-addons/base-python/aarch64:latest"
  amd64: "ghcr.io/hassio-addons/base-python/amd64:latest"
  armhf: "ghcr.io/hassio-addons/base-python/armhf:latest"
  armv7: "ghcr.io/hassio-addons/base-python/armv7:latest"
  i386: "ghcr.io/hassio-addons/base-python/i386:latest"
