name: YouTube Audio Streaming
version: "1.0.4"
slug: youtube_audio_streaming
description: Stream audio from YouTube videos
arch:
  - amd64
startup: application
boot: auto
ports:
  5000/tcp: 5000
options: {}
schema: {}
