name: YouTube Audio Streaming
version: "1.1.14"
slug: youtube_audio_streaming
description: Stream audio from YouTube videos with web interface
url: https://github.com/paulsteigel/ha-chatbot-server.git
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 5005
panel_icon: "mdi:youtube"
ports:
  5005/tcp: 5005
ports_description:
  5005/tcp: "YouTube Audio Streaming API"
options: {}
schema: {}
