name: YouTube Audio Streaming
version: "1.0.3"
slug: youtube_audio_streaming
description: Stream audio from YouTube videos
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  5000/tcp: 5000
options: {}
schema: {}
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.20
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.20
  armhf: ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.20
  armv7: ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.20
  i386: ghcr.io/home-assistant/i386-base-python:3.13-alpine3.20
