name: HA Entity Endpoint
version: "1.0.0"
slug: ha-entity-endpoint
description: API endpoint for remote devices to query HA entities and control devices
url: https://github.com/paulsteigel/ha-chatbot-server
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5003/tcp: 5003
ports_description:
  5003/tcp: API endpoint port
options:
  access_token: ""
  ha_url: "http://supervisor/core"
schema:
  access_token: str
  ha_url: str
homeassistant_api: true
hassio_api: true
hassio_role: default
