name: HA Entity Endpoint
version: "1.0.1"
slug: ha-entity-endpoint
description: API endpoint for remote devices to query HA entities
url: https://github.com/paulsteigel/ha-chatbot-server
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: python:{arch}-3.11-alpine
ports:
  5003/tcp: 5003
options:
  access_token: ""
  ha_url: "http://supervisor/core"
schema:
  access_token: str
  ha_url: str
homeassistant_api: true
